#ddev-generated

# https://github.com/delfer/docker-alpine-ftp-server

services:
  ftp:
    container_name: ddev-${DDEV_SITENAME}-ftp
    image: delfer/alpine-ftp-server
    restart: "no"
    expose:
      - 21
      - 21000-21010
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - USERS=ftpuser|ftPassw0rd
      - MIN_PORT=21000
      - MAX_PORT=21010
      - ADDRESS=ftp
    volumes:
      - ./ftp/data:/ftp/ftpuser
      - ftp:/ftp/ftp

volumes:
  ftp:
    name: "${DDEV_SITENAME}-ftp"